### PR TITLE
Introduce Netlink Library/Use sd-bus/ Code refactor and cleanups.

### PR DESCRIPTION
**Pull request by ssahani**
This work enhances netmgr.

1. Introduces minimal netlink library.
2. fix bunch of compiler warning/erros.
3. drop ioctls calls use netlink.
4. use sd-bus API to interact with systemd.
5. use gcc cleanup macro.

### CODE REVIEW

**Comment by ssahani** [comment]
ping

**Comment by ssahani** [comment]
@YustasSwamp PTAL

**Comment by ppadmavilasom** [comment]
@ssahani thanks for the PR. sorry for the delay. if you would be kind enough to reopen, we would like to open this for review

**Comment by ssahani** [comment]
@ppadmavilasom Thanks for Looking into it. I have few more enhancements . will just rework all of these again and open a fresh set of prs.

**Pull request closed without merging**
